-- drop database peliculasBD;
 
CREATE DATABASE IF NOT EXISTS peliculasBD;
USE peliculasBD;
-- Tabla Generos
CREATE TABLE Generos (
    ID_Genero INT AUTO_INCREMENT PRIMARY KEY,
    Nombre_Genero VARCHAR(50) NOT NULL UNIQUE -- Evitar géneros duplicados
);
CREATE TABLE Clasificacion (
    ID_Clasificacion INT AUTO_INCREMENT PRIMARY KEY,
    ClasificacionDePelicula VARCHAR(50) NOT NULL UNIQUE -- Evitar géneros duplicados
);
-- Tabla Peliculas
CREATE TABLE Peliculas (
    ID_Pelicula INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    LinkTrailer VARCHAR(500) NOT NULL,
    Duracion varchar(5) NOT NULL,
    Anio_Salida YEAR NOT NULL,
    Resumen TEXT NOT NULL,
    ID_Genero INT NOT NULL,
	ID_Clasificacion INT NOT NULL,
    Calificacion DECIMAL(3,1) NOT NULL DEFAULT 0.0, -- Valor por defecto
    FOREIGN KEY (ID_Genero) REFERENCES Generos(ID_Genero)
    ON DELETE CASCADE, -- Eliminar en cascada si el género se elimina
    FOREIGN KEY (ID_Clasificacion) REFERENCES Clasificacion(ID_Clasificacion)
    ON DELETE CASCADE, -- Eliminar en cascada si el género se elimina
    CONSTRAINT chk_calificacion CHECK (Calificacion BETWEEN 0 AND 10) -- Restringir rango
);

INSERT INTO Clasificacion (ClasificacionDePelicula) VALUES ('A'), ('B'), ('C');
 
-- Insertar géneros únicos
INSERT INTO Generos (Nombre_Genero) VALUES ('Acción'), ('Drama'), ('Ciencia Ficción'), ('Suspenso'), ('Anime'), ('Animacion');
-- Insertar películas con calificación válida
INSERT INTO Peliculas (Nombre, LinkTrailer , Duracion, Anio_Salida, Resumen, ID_Genero, ID_Clasificacion, Calificacion)
VALUES 
('Sueño de Fuga', 'https://www.youtube.com/embed/-FO-0tKQ2SY?si=3BOY5WSlfumruvUR', '02:22', 1994, 
'Andy Dufresne, un banquero exitoso, es condenado a cadena perpetua por un crimen que no cometió. En la prisión de Shawshank, su vida comienza a cambiar mientras intenta adaptarse a su nueva realidad. A lo largo de los años, forja una inesperada amistad con Ellis Redding, un prisionero veterano. Con el tiempo, Andy demuestra su habilidad para la contabilidad y comienza a ayudar al director de la prisión con sus finanzas, lo que le otorga cierto poder dentro de la institución. Sin embargo, su deseo de redención y de escapar de la injusticia lo impulsa a idear un plan audaz para escapar. Este es un relato sobre la esperanza, la amistad, la resistencia y el poder de la mente humana para superar incluso las situaciones más desesperadas.', 2, 1, 9.3),
('El Padrino', 'https://www.youtube.com/embed/iOyQx7MXaz0?si=XXutIpDI81TIRprf', '02:55', 1972, 
'Don Vito Corleone, el patriarca de la familia mafiosa Corleone, es un hombre de gran influencia en Nueva York. Después de un atentado en su contra, su hijo Michael, inicialmente ajeno a los negocios de la familia, se ve obligado a involucrarse en el mundo criminal para proteger a su padre. La historia sigue la evolución de Michael, quien, a pesar de sus intentos de alejarse de la mafia, se convierte en el líder de la familia después de la muerte de su padre. La saga narra las luchas de poder dentro de la familia, los sacrificios personales y las consecuencias de la lealtad y la venganza, mientras Michael toma decisiones que lo cambian para siempre. "El Padrino" es un relato profundo sobre la familia, el poder, el crimen y el honor.', 1, 1, 9.2),
('El Caballero de la Noche', 'https://www.youtube.com/embed/dzQtWkpc2-c?si=e1kPmATjx6rqaVOz', '02:32', 2008, 
'Batman, el Caballero Oscuro, se enfrenta a su mayor desafío cuando un nuevo villano, el Joker, aparece en Gotham City. El Joker es un criminal impredecible y caótico que busca sumergir a la ciudad en el caos, desafiando la moral y el orden establecido. Mientras Batman lucha por detenerlo, el dilema ético de la justicia se pone en juego, ya que el Joker no solo es una amenaza física, sino también una prueba psicológica para el héroe. Además, Harvey Dent, el fiscal de distrito de Gotham, se convierte en una víctima de la corrupción del crimen, transformándose en el villano Dos Caras. La película explora temas de sacrificio, moralidad y la línea difusa entre el bien y el mal.', 4, 2, 9.0),
('Forrest Gump', 'https://www.youtube.com/embed/Cyh1LpxnaxI?si=oInjffKOFwU_PKMN', '02:22', 1994, 
'Forrest Gump es un hombre con un coeficiente intelectual por debajo del promedio, pero con un corazón puro y una extraordinaria capacidad para superar las adversidades. A lo largo de su vida, se ve envuelto en eventos históricos y momentos cruciales, desde la guerra de Vietnam hasta la creación de una de las compañías más exitosas del país. Su vida es una serie de coincidencias, pero también de decisiones impulsadas por su amor inquebrantable por Jenny, una mujer que ha sido una constante en su vida. Aunque la vida le ofrece oportunidades extraordinarias, Forrest permanece fiel a sí mismo y a sus valores. Su historia es una reflexión sobre el destino, la determinación y la simplicidad de los momentos más significativos de la vida.', 3, 1, 8.8),
('Tiempos Violentos', 'https://www.youtube.com/embed/s7EdQ4FqbhY?si=L9zJHZSwNMYoyZAc', '02:34', 1994, 
'"Tiempos Violentos" entrelaza varias historias de crimen y violencia en Los Ángeles, conectando a personajes de diferentes mundos de la ciudad. La película sigue a Vincent Vega y Jules Winnfield, dos asesinos a sueldo al servicio de Marsellus Wallace, un poderoso gánster. A lo largo de la película, los personajes se enfrentan a situaciones de vida o muerte, y sus historias se cruzan de manera inesperada. Desde un robo en un restaurante hasta las consecuencias de un accidente mortal, "Tiempos Violentos" explora la naturaleza impredecible de la vida, la violencia y las decisiones que cambian el curso de la existencia de los personajes, todo narrado con la característica mezcla de humor negro y tensión de Quentin Tarantino.', 1, 2, 8.9),
('La Lista de Schindler', 'https://www.youtube.com/embed/7q-ETFeMxwI?si=McuKvttaxuN2tSdL', '03:15', 1993, 
'Oskar Schindler, un empresario alemán, se convierte en un héroe inesperado durante el Holocausto, al salvar la vida de más de mil judíos. Al principio motivado por el deseo de obtener beneficios personales, Schindler comienza a darse cuenta de la magnitud de la tragedia y el sufrimiento de los prisioneros judíos. A medida que se adentra más en la barbarie del régimen nazi, arriesga su propia vida para proteger a aquellos que trabajan para él, finalmente convirtiéndose en un símbolo de la humanidad en medio de la oscuridad. La película es un testimonio poderoso sobre la capacidad de un hombre para hacer el bien incluso en las circunstancias más desesperadas y sobre la importancia de la memoria histórica.', 2, 1, 9.0),
('El Señor de los Anillos El Retorno del Rey', 'https://www.youtube.com/embed/h-9RYiqyqjk?si=ubilSz49oMQpyNq_', '03:21', 2003, 
'En la conclusión épica de la trilogía, la guerra por la Tierra Media llega a su punto culminante. Mientras Frodo y Sam continúan su viaje hacia el Monte del Destino para destruir el Anillo Único, Aragorn, Legolas y Gimli lideran las fuerzas de la humanidad en una batalla final contra el ejército de Sauron. Las fuerzas oscuras parecen invencibles, pero la valentía y la determinación de los héroes son la última esperanza para salvar la Tierra Media. La historia culmina en un sacrificio final, la destrucción del Anillo y el regreso de la paz. "El Retorno del Rey" es un relato sobre la lucha contra el mal, el sacrificio personal y la importancia de la amistad y la lealtad en tiempos de adversidad.', 4, 1, 9.0),
('El Club de la Pelea', 'https://www.youtube.com/embed/YD5BeUWgsSM?si=Bv7Q7bwsPFnedu_h', '02:19', 1999, 
'Un hombre insatisfecho con su vida, conocido solo como el "Narrador", se encuentra con Tyler Durden, un carismático hombre que le introduce a un mundo de caos y destrucción. Juntos, fundan el Club de la Pelea, un espacio clandestino donde hombres frustrados pueden liberar sus tensiones a través de peleas físicas. Sin embargo, lo que comienza como una forma de escape se convierte rápidamente en algo mucho más grande y peligroso, cuando Tyler se convierte en líder de un grupo radical llamado "Proyecto Caos", que busca destruir las estructuras sociales y económicas. A medida que la historia avanza, el narrador descubre secretos oscuros sobre su relación con Tyler y el impacto de sus acciones. La película aborda temas como la masculinidad, la alienación y la lucha interna por encontrar un propósito en la vida.', 1, 2, 8.8),
('Matrix', 'https://www.youtube.com/embed/Pl_H2Lmjn6k?si=TuBNc6jIve1BvrcZ', '02:16', 1999, 
'Thomas Anderson, un programador de computadoras que lleva una vida ordinaria como hacker, descubre que el mundo en el que vive no es real. Es un sistema simulado conocido como la "Matrix", creado por máquinas inteligentes para controlar a la humanidad. Un misterioso grupo de rebeldes, liderados por Morfeo, le revela la verdad y le da la oportunidad de liberarse de la Matrix y unirse a la resistencia. Mientras Anderson se convierte en Neo, el elegido, se enfrenta a la misión de destruir el sistema y salvar a la humanidad. La película explora conceptos filosóficos sobre la realidad, el control y el libre albedrío, mientras Neo descubre su verdadero poder.', 4, 2, 8.2), 
('Buenos Muchachos', 'https://www.youtube.com/embed/UistGQBVotg?si=vZU1EkFZek5qEYx4', '02:28', 1990, 
'La historia sigue la vida de Henry Hill, un joven que se enamora del mundo del crimen organizado en Nueva York. A medida que crece, se convierte en parte integral de una de las familias mafiosas más poderosas, los Lucchese. A través de su relato, el público ve el ascenso y la caída de Henry dentro del mundo criminal, desde los primeros delitos menores hasta los crímenes más grandes. El relato está salpicado de momentos de acción, lealtad, traición y el impacto del estilo de vida mafioso en la vida personal y familiar. La película explora la atracción del crimen, la lealtad a los amigos y las consecuencias que inevitablemente llegan cuando uno se adentra en este mundo.', 1, 1, 8.7),
('Interestelar', 'https://www.youtube.com/embed/LYS2O1nl9iM?si=rPk6qm3kCCHQMyUO', '02:49', 2014, 
'En un futuro cercano, la Tierra se enfrenta a la extinción debido a la escasez de recursos y las condiciones climáticas extremas. Cooper, un piloto y ingeniero, es reclutado para un viaje espacial en busca de un nuevo hogar para la humanidad. A bordo de una nave espacial, viaja a través de un agujero de gusano en el espacio-tiempo, descubriendo mundos desconocidos. Mientras tanto, en la Tierra, su hija Murph intenta resolver un misterio relacionado con la gravedad que podría ser la clave para salvar a la humanidad. "Interestelar" es una exploración de la ciencia, el amor, la sacrificio y la supervivencia.', 4, 2, 8.6),
('Pecados Capitales', 'https://www.youtube.com/embed/xhzBmjdehPA?si=sc1meys9UAXKIvnV', '02:07', 1995, 
'En esta inquietante historia, dos detectives investigan una serie de asesinatos que siguen el patrón de los siete pecados capitales. El veterano detective Somerset y el joven detective Mills son asignados a la investigación, mientras el asesino, conocido como "John Doe", deja pistas cada vez más perturbadoras en la escena de cada crimen. A medida que se acercan al asesino, el caso se convierte en una carrera contrarreloj para detenerlo antes de que complete su macabra obra. "Pecados Capitales" explora temas profundos sobre la moralidad, el castigo y el impacto del pecado en la sociedad y los individuos.', 1, 2, 8.6),
('Gladiador', 'https://www.youtube.com/embed/lsDdsvKVbMo?si=3tke60UhPhMaCpCk', '02:35', 2000, 
'Maximus Decimus Meridius, un general romano leal al emperador, es traicionado por el hijo del emperador, Cómodo, quien asesina a su padre y toma el trono. Maximus es capturado y vendido como esclavo, pero su deseo de venganza lo lleva a convertirse en un gladiador en las arenas del Coliseo. A medida que avanza en la lucha por su vida, se convierte en un héroe popular y finalmente enfrenta a Cómodo en un enfrentamiento épico que definirá el destino del Imperio Romano. "Gladiador" es una historia de honor, venganza y sacrificio en la antigua Roma.', 3, 2, 8.5),
('El Silencio de los Inocentes', 'https://www.youtube.com/embed/Psd65AeD9RI?si=7dGkXsb5JeiA6Qz7', '01:58', 1991, 
'La joven agente del FBI, Clarice Starling, es asignada para entrevistar a Hannibal Lecter, un asesino en serie brillante pero extremadamente peligroso, que está en prisión. Mientras trabaja con Lecter para obtener información sobre otro asesino conocido como "Buffalo Bill", Clarice desarrolla una relación compleja con Lecter, quien le ofrece pistas a cambio de información personal. A medida que el caso se complica, Clarice debe enfrentar sus propios demonios mientras se enfrenta a los horrores de su trabajo y las revelaciones que Lecter hace. "El Silencio de los Inocentes" es un thriller psicológico que explora la psicología del crimen y la justicia.', 1, 2, 8.6),
('Rescatando al Soldado Ryan', 'https://www.youtube.com/embed/S1Qj_AVu2pA?si=EcH9Di5V0WHSi3Ae', '02:49', 1998, 
'Durante la invasión de Normandía en la Segunda Guerra Mundial, el capitán Miller y su escuadrón de élite son enviados en una misión arriesgada: encontrar y traer de vuelta al soldado James Francis Ryan, cuyo paradero es desconocido. Su madre ha recibido la noticia de la muerte de sus tres hijos, y el ejército decide hacer todo lo posible por traer de vuelta al último hijo sobreviviente. Mientras avanzan a través de territorio enemigo, los soldados enfrentan desafíos mortales, el temor y el sacrificio personal. "Rescatando al Soldado Ryan" es un poderoso testimonio del coraje y la humanidad en medio de la guerra.', 2, 1, 8.6),
('Milagros Inesperados', 'https://www.youtube.com/embed/WieEyu5KDbE?si=jXrHWSiqEW9udS5k', '03:09', 1999, 
'Paul Edgecomb, un guardia de prisión, trabaja en el bloque de ejecuciones donde conoce a un prisionero llamado John Coffey, un hombre con habilidades extraordinarias. Aunque Coffey ha sido condenado por el asesinato de dos niñas, pronto se hace evidente que tiene un poder sobrenatural para curar a otros. A medida que Paul y su equipo de trabajo se dan cuenta de los dones de Coffey, empiezan a cuestionar su culpabilidad y se enfrentan a un dilema moral. "Milagros Inesperados" es una reflexión sobre la vida, la muerte, la redención y la inexplicable bondad en medio de la oscuridad.', 3, 1, 8.6),
('Star Wars Una Nueva Esperanza', 'https://www.youtube.com/embed/_sQSHZ65fPI?si=mbS-k5Xz3hTNDTvg', '02:01', 1977, 
'En una galaxia muy, muy lejana, un joven llamado Luke Skywalker se embarca en una misión para derrotar al Imperio Galáctico, liderado por Darth Vader. Con la ayuda de un contrabandista llamado Han Solo, la Princesa Leia y un grupo de aliados, Luke intenta destruir la estación espacial más poderosa de la galaxia, la Estrella de la Muerte. A lo largo de la aventura, Luke descubre que es el hijo de un Jedi y comienza su entrenamiento para convertirse en un Caballero Jedi, enfrentándose a Vader en una batalla épica. "Star Wars: Una Nueva Esperanza" es un clásico de la ciencia ficción que combina aventura, acción y la eterna lucha entre el bien y el mal.', 4, 1, 8.6),
('Los Vengadores', 'https://www.youtube.com/embed/An_NsOddM3o?si=LDuqsuyIKpxf4STJ', '02:23', 2012, 
'Cuando una amenaza cósmica en forma de Loki, el hermano adoptivo de Thor, llega a la Tierra, Nick Fury, el director de S.H.I.E.L.D., decide reunir a un grupo de héroes para defender el planeta. Los Vengadores incluyen a Iron Man, Capitán América, Thor, Hulk, Viuda Negra y Hawkeye, quienes deben trabajar juntos para detener a Loki y su ejército alienígena. Sin embargo, la unión de estos héroes no es fácil debido a sus personalidades y egos conflictivos. "Los Vengadores" es una película de acción épica que celebra la cooperación, la heroísmo y la lucha por el bien común.', 4, 2, 8.0),
('Jurassic Park', 'https://www.youtube.com/embed/dLDkNge_AhE?si=mZb_5fbrRcyEYR0b', '02:07', 1993, 
'En una isla remota, un multimillonario crea un parque temático en el que los dinosaurios, traídos de vuelta a la vida mediante ingeniería genética, son las principales atracciones. Cuando un grupo de expertos visita el parque para verificar su seguridad, un fallo en los sistemas de seguridad provoca que los dinosaurios escapen y pongan en peligro a todos. La historia sigue a un grupo de personajes que deben sobrevivir mientras luchan por escapar de los dinosaurios y evitar que el desastre se extienda más allá de la isla. "Jurassic Park" es una mezcla de ciencia ficción y aventura que explora las consecuencias imprevistas de la ciencia y la ambición humana.', 4, 2, 8.1),
('Titanic', 'https://www.youtube.com/embed/FiRVcExwBVA?si=H3RR2pjPNHPwsycy', '03:14', 1997, 
'En esta épica historia de amor, Jack y Rose, dos pasajeros de diferentes clases sociales, se encuentran a bordo del lujoso barco Titanic durante su fatídico viaje inaugural. Mientras se desarrolla su romance, el barco colisiona con un iceberg y comienza a hundirse. A lo largo de la tragedia, los dos luchan por sobrevivir mientras el desastre se despliega a su alrededor. "Titanic" no solo es un relato de amor prohibido, sino también una mirada a la valentía, el sacrificio y el caos de un evento histórico devastador.', 3, 1, 7.9),
('El Rey León', 'https://www.youtube.com/embed/h-As2lUk6IA?si=BGsrBv72qw47HjCe', '01:28', 1994, 
'La historia de Simba, un joven león destinado a ser rey, que debe enfrentarse a su destino tras la trágica muerte de su padre, Mufasa, a manos de su malvado tío Scar. A lo largo de su viaje, Simba se aleja de su hogar y vive una vida de exilio, hasta que finalmente regresa para reclamar su lugar como líder de la Sabana Africana. "El Rey León" es una emotiva historia sobre la familia, la responsabilidad y el ciclo de la vida, mientras Simba aprende a asumir su papel como rey y protector de su reino.', 5, 1, 8.5),
('Toy Story', 'https://www.youtube.com/embed/v-PjgYDrg70?si=faWi9Ogq6xc3i2vQ', '01:21', 1995, 
'La historia sigue a Woody, un vaquero de juguete que es el favorito de su dueño, Andy. Sin embargo, cuando Andy recibe un nuevo juguete, Buzz Lightyear, un astronauta de acción, Woody siente celos y se ve desplazado. Mientras los dos intentan llevarse bien, un accidente los lleva fuera de la casa, y ahora deben trabajar juntos para regresar antes de que Andy se mude a su nueva casa. "Toy Story" es una aventura llena de amistad, celos y valentía, donde los juguetes cobran vida y enfrentan sus propios desafíos.', 5, 1, 8.3),
('Buscando a Nemo', 'https://www.youtube.com/embed/ic53iM_WZWs?si=iBFzJfYivfu1Qbm2', '01:40', 2003, 
'Marlin, un pez payaso, emprende una épica búsqueda por el océano para encontrar a su hijo, Nemo, quien fue capturado por un buzo y llevado a un acuario. A lo largo de su aventura, Marlin es acompañado por Dory, un pez con problemas de memoria, y juntos enfrentan una serie de peligros y desafíos. Mientras tanto, Nemo hace nuevos amigos en su cautiverio, mientras planea su escape. "Buscando a Nemo" es una conmovedora historia sobre la paternidad, el coraje y la importancia de nunca rendirse, sin importar los obstáculos que se presenten.', 5, 1, 8.1),
('Up Una Aventura de Altura', 'https://www.youtube.com/embed/ORFWdXl_zJ4?si=ncoxEgaVqEd0V-zj', '01:36', 2009, 
'Carl Fredricksen, un anciano viudo, cumple el sueño de su difunta esposa Ellie de viajar a Sudamérica, atando miles de globos a su casa para volar. Sin embargo, descubre que accidentalmente ha llevado consigo a un niño llamado Russell, un joven explorador que busca ganar una medalla de mérito. Juntos enfrentan una serie de aventuras mientras exploran las maravillas de la selva. "Up" es una emotiva historia sobre la amistad, la superación y la importancia de seguir adelante, incluso cuando el futuro parece incierto.', 5, 1, 8.2),
('Coco', 'https://www.youtube.com/embed/awzWdtCezDo?si=H-cVv9mPB-3GLXFG', '01:45', 2017, 
'Miguel, un niño que sueña con ser músico, viaja al Mundo de los Muertos para descubrir la verdad sobre su familia y su misterioso vínculo con su tatarabuelo, un músico famoso. A lo largo de su aventura, Miguel encuentra la importancia de la familia y aprende lecciones sobre el legado, el perdón y el significado de las tradiciones familiares. "Coco" es una emotiva y colorida historia sobre la muerte, la memoria y el poder de la música en la cultura mexicana.', 5, 1, 8.4);